services:
  ui:
    container_name: ui
    build: ./web_frontend
    expose: # CURRENTLY CONFIGURED FOR PRODUCTION NGINX ENVIRONMENT -> CHANGE TO `port: - 3000:3000` for localhost without docker copntainerization
      - 3000
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    expose: # CURRENTLY CONFIGURED FOR PRODUCTION NGINX ENVIRONMENT -> CHANGE TO `port: - 3001:3001` for localhost without docker copntainerization
      - 3001
    depends_on:
      - mongo

  mongo:
    container_name: db
    image: mongo
    volumes:
      - mongo-volume:/data/db
    expose:
      - 27017
  
volumes:
  mongo-volume: