services:
  ui:
    container_name: ui
    build: ./web_frontend
    expose:
      - 3000
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend
    expose:
      - 3001
    depends_on:
      - mongo

  mongo:
    container_name: db
    image: mongo
    volumes:
      - mongo-volume:/data/db
    ports:
      - 27017:27017
  
volumes:
  mongo-volume: